version: "3.4"

services: 
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - "80:80"
    depends_on:
      - "app1"
      - "app2" 
      - "app3"
  
  app1:
    container_name: app1
    build: .
    ports: 
      - "8080"
  
  app2:
    container_name: app2
    build: .
    ports: 
      - "8080"

  app3:
    container_name: app3
    build: .
    ports: 
      - "8080"